name: nix

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  nix:
    runs-on: [self-hosted, Linux, X64, tweag-infra]
    strategy:
      fail-fast: false
      matrix:
        target:
          - required.formattingLinting
          - required.native

    steps:
      - uses: actions/checkout@v6

      - name: Build ${{ matrix.target }}
        run: nix build .#hydraJobs.x86_64-linux.${{ matrix.target }} --print-build-logs

